# inventory.tpl
all:
  children:
    spark_cluster:
      children:
        master:
          hosts:
            spark-master:
              ansible_host: 10.216.151.62
        workers:
          hosts:
            spark-worker-1:
              ansible_host: 10.216.151.139
            spark-worker-2:
              ansible_host: 10.216.151.220
      vars:
        ansible_user: debian
        ansible_password: debian
        ansible_become_password: debian
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'